### ISSUE TITLE
Failed at the pkcs11js@1.0.10 install Script

### ISSUE THREAD

**Issue by hwegge2** [PeculiarVentures/pkcs11js#21]
It Appears every time I am trying to build a project with pkcs11js as a dependency, it fails upon tying to execute the install scripts.

**Comment by microshine** [comment]
@hwegge2 Could you share installation log?

**Comment by hwegge2** [comment]
It appears that it was an issue with permissions at the OS level. 
This was resolved with the following command on Ubuntu 16.04

`sudo npm install -g PACKAGE-NAME --unsafe-perm=true --allow-root`

**Comment by mhamzawey** [comment]
Is this issue solved.  I still get the same error and i've tried everything posted but no luck.

**Comment by microshine** [comment]
@mhamzawey can you share npm log with error?
