### ISSUE TITLE
Docker image Alpine unable to Install pkcs11js 

### ISSUE THREAD

**Issue by anish-edx** [PeculiarVentures/pkcs11js#74]
Node Image : node:12.20.2-alpine3.12

Alpine Package Installed: alpine-sdk libc-dev libressl-dev make autoconf automake libtool sqlite pkgconfig p11-kit-dev build-base python2 python2-dev openssl cppunit-dev botan-dev

I am getting this error when running npm install in my project directory.

`
`
    Step 7/12 : RUN npm install pkcs11js
    ---> Running in fbe8340e23ca

    pkcs11js@1.2.0 install /usr/src/app/node_modules/pkcs11js
    node-gyp rebuild

    make: Entering directory '/usr/src/app/node_modules/pkcs11js/build'
    CXX(target) Release/obj.target/pkcs11/src/main.o
    In file included from ../../nan/nan.h:56,
    from ../src/main.cpp:1:
    /root/.cache/node-gyp/12.20.2/include/node/node.h:737:43: warning: cast between incompatible function types from 'void ()(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)' {aka 'void ()(v8::Localv8::Object)'} to 'node::addon_register_func' {aka 'void ()(v8::Localv8::Object, v8::Localv8::Value, void)'} [-Wcast-function-type]
    737 | (node::addon_register_func) (regfunc),
     | ^
    /root/.cache/node-gyp/12.20.2/include/node/node.h:771:3: note: in expansion of macro 'NODE_MODULE_X'
    771 | NODE_MODULE_X(modname, regfunc, NULL, 0) // NOLINT (readability/null_usage)
    | ^~~~~~~~~~~~~
     ../src/main.cpp:27:1: note: in expansion of macro 'NODE_MODULE'
    27 | NODE_MODULE(pkcs11, init)
    | ^~~~~~~~~~~
    CXX(target) Release/obj.target/pkcs11/src/dl.o
    CXX(target) Release/obj.target/pkcs11/src/const.o
    CXX(target) Release/obj.target/pkcs11/src/pkcs11/error.o
    CXX(target) Release/obj.target/pkcs11/src/pkcs11/v8_convert.o
    CXX(target) Release/obj.target/pkcs11/src/pkcs11/template.o
    CXX(target) Release/obj.target/pkcs11/src/pkcs11/mech.o
    CXX(target) Release/obj.target/pkcs11/src/pkcs11/param.o
    CXX(target) Release/obj.target/pkcs11/src/pkcs11/param_aes.o
    CXX(target) Release/obj.target/pkcs11/src/pkcs11/param_rsa.o
    CXX(target) Release/obj.target/pkcs11/src/pkcs11/param_ecdh.o
    CXX(target) Release/obj.target/pkcs11/src/pkcs11/pkcs11.o
    CXX(target) Release/obj.target/pkcs11/src/async.o
    CXX(target) Release/obj.target/pkcs11/src/node.o
    SOLINK_MODULE(target) Release/obj.target/pkcs11.node
    COPY Release/pkcs11.node
    make: Leaving directory '/usr/src/app/node_modules/pkcs11js/build'
    npm notice created a lockfile as package-lock.json. You should commit this file.
 
    pkcs11js@1.2.0
    added 2 packages from 9 contributors and audited 2 packages in 41.651s`

**Comment by microshine** [comment]
I published the new version `v1.2.2`. Please try it. Does it fix your problem?

**Comment by anish-edx** [comment]
The issue still persists with the alpine image. 
![pkcs11js@1 2 2](https://user-images.githubusercontent.com/67774629/110432387-0da15b80-80d5-11eb-94a7-20df976c1931.png)

**Comment by microshine** [comment]
I can't reproduce your error

Just tried to build Docker images for NodeJs v12 and v14

I don't have any problems and warnings

![image](https://user-images.githubusercontent.com/7333669/110454559-70e0bd00-80d8-11eb-90a2-3beee4a31019.png)

The interesting thing in your screenshot is that it doesn't have errors (just warnings) and `pkcs11js.node` library was compiled and copied to the `Release` directory

**Comment by anish-edx** [comment]
> I can't reproduce your error
> 
> Just tried to build Docker images for NodeJs v12 and v14
> 
> I don't have any problems and warnings
> 
> ![image](https://user-images.githubusercontent.com/7333669/110454559-70e0bd00-80d8-11eb-90a2-3beee4a31019.png)
> 
> The interesting thing in your screenshot is that it doesn't have errors (just warnings) and `pkcs11js.node` library was compiled and copied to the `Release` directory

Use alpine image : 

FROM node:12.20.2-alpine3.12

**Comment by microshine** [comment]
It shows warnings but it works

Scripts prints exprorts from the `pkcs11js` module
![image](https://user-images.githubusercontent.com/7333669/110692181-2013b600-81f7-11eb-8ebc-dbe63e2c1bda.png)

**Comment by anish-edx** [comment]
@microshine Thanks for the help, It works. Also, I added one Env var and the warning disappear.

`  ENV CXXFLAGS="-Wno-cast-function-type"  `

![pkcs11](https://user-images.githubusercontent.com/67774629/110736361-82010980-8251-11eb-9286-25c8d95cf0d5.png)
